Title
WebDizainStudio/s-chistogo-lista pull request #1
Opened 2023-06-12 11:49 UTC by WebDizainStudio

2023-06-12 15:28 UTC, Avaakum requested changes
Доброго времени суток. У вас получилась хорошая работа!

*Что понравилось:*

- хорошие стили
- используется семантика
- Используются списки

*Что необходимо исправить:*

- **Все комментарии в коде, кроме тех, которые с пометкой "можно лучше" и "отлично"**
- Отличия от макета:
   -  https://disk.yandex.ru/i/aC_lJ78g6ItBBQ логотип не отображается
   -  https://disk.yandex.ru/i/DwMR9n3QIgUTfQ 2 фото не отображаются
   -  https://disk.yandex.ru/i/p3Aq_m9XVgS92w текст сильно сдвинут вправо
   -  https://disk.yandex.ru/i/8aNuq3PF1Vkx9A текст сильно сдвинут вправо
   -  https://disk.yandex.ru/i/yFXLSpI9eubf2A размер шрифта ссылок

*Что можно улучшить:*

- Все комментарии "Можно лучше"
- Желательно использовать все классы по БЭМ
  - https://ru.bem.info/methodology/quick-start/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 

**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2023-06-12 15:28 UTC, Avaakum commented on fonts/fonts.css
> +  font-family: 'EB Garamond';
При подключении определённого начертания шрифта необходимо указывать уточняющие параметры для шрифта(font-weight, font-style) или браузер не будет знать, что это за начертание. Сейчас второе правило @font-face перебивает первое по специфике CSS. 

**Нужно задать эти параметры, или хотя бы font-weight для каждого начертания шрифта.** 

Тут [подробнее](https://developer.mozilla.org/ru/docs/Web/CSS/font-weight#%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2%D0%B5%D1%81%D0%B0_%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8), как понять какой вес шрифта у этого файла по названию файла. А так же:

- https://developer.mozilla.org/ru/docs/Web/CSS/font-weight 
- https://developer.mozilla.org/ru/docs/Web/CSS/font-style

2023-06-12 15:28 UTC, Avaakum commented on styles/style.css
> +	font-family: 'EB Garamond', 'Arial', sans-serif;
Тут не подходит Arial как альтернативный шрифт, т.к. это шрифт без засчечек. А так же тип засечек sans-serif некорректный, используйте serif - шрифт по-умолчанию "с засечками".

---

 - В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта) , где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек.

2023-06-12 15:28 UTC, Avaakum commented on styles/style.css
> +	font-family: 'EB Garamond', 'Arial', sans-serif;
Тут не подходит Arial как альтернативный шрифт, т.к. это шрифт без засчечек. А так же тип засечек sans-serif некорректный, используйте serif - шрифт по-умолчанию "с засечками".

2023-06-12 15:28 UTC, Avaakum commented on styles/style.css
> +	font-family: 'EB Garamond', 'Arial', sans-serif;
Тут не подходит Arial как альтернативный шрифт, т.к. это шрифт без засчечек. А так же тип засечек sans-serif некорректный, используйте serif - шрифт по-умолчанию "с засечками".

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +			<img src="./logo.svg" alt="logo" class="header__logo-image">
Используется некорректный относительный маршрут, файл не найден. Нужно внимательно проверить, из каких директорий в маршруте вы выходите, а в какие входите.


---

**Так должны начинаться все маршруты до файлов в проекте в HTML и CSS:**

- `./` означает, что мы начитаем относительный маршрут  до файла в этой же папке или ниже по иерархии папок, например `'./file.jpg'` 
- `../` означает, что мы сначала выходим из папки в которой находимся чтобы например зайти в другую папку, или выйти еще выше по иерархии `../../folder/` , чтобы из текущего положения, где находится файл в котором подключают, добраться до нужного файла который подключают.


---

Хорошо бы избегать использования абсолютных путей. 
 Использование абсолютного пути приводит к тому, что файлы проекта становятся зависимы от директории вашего проекта, а также от уровня, на котором они располагаются. 
Например, если указать все пути к файлам, начиная от директории вашего проекта `/your-project/`, то разместив их в другой директории или загрузив на сервер - они будут недоступны и не загрузятся. 

Используйте корректные относительные пути в своей работе.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +								<img src="./polyarinov.png" alt="">
- Используется некорректный относительный маршрут, файл не найден. Нужно внимательно проверить, из каких директорий в маршруте вы выходите, а в какие входите при подключении файла.
- Альтернативное описание для тега img должно быть на языке страницы(русский). Альтернативное описание картинки должно объяснять что находится на этой картинке. Оно часто используется людьми с проблемами зрения, которые используют специальные читалки, где все картинки будут   описаны через альтернативный текст. Также хорошее описание картинок помогает для индексации страницы поисковыми системами.    Исключения: логотипы английских брендов. Например у иконки Instagram допустим alt на английском.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +								<img src="./polyarinov.png" alt="">
- Используется некорректный относительный маршрут, файл не найден. Нужно внимательно проверить, из каких директорий в маршруте вы выходите, а в какие входите при подключении файла.
- Тут должна быть другая фотография
- Альтернативное описание для тега img должно быть на языке страницы(русский). Альтернативное описание картинки должно объяснять что находится на этой картинке. Оно часто используется людьми с проблемами зрения, которые используют специальные читалки, где все картинки будут   описаны через альтернативный текст. Также хорошее описание картинок помогает для индексации страницы поисковыми системами.    Исключения: логотипы английских брендов. Например у иконки Instagram допустим alt на английском.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +				<li class="header__menu-item header__menu-item_active">
---

**Можно лучше:**

Так как мы для ссылки сбрасываем подчёркивание для активного пункта меню, то можно присвоить модификатор сразу для ссылки и не использовать составной селектор в CSS

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +			<ul class="header__menu-list">
---

**Отлично:**

Отличная семантика и структура

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +				<div class="intro__date">
Используйте для даты семантический тег time. Подробнее о нем [почитайте на Доке](https://doka.guide/html/time/).

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +			<div class="content-section__introduction">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +			<div class="content-section__introduction">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__author-photo">
Лишний div, присвойте класс сразу картинке

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__author-photo">
Лишний div, присвойте класс сразу картинке

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__author-name">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__author-name">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__text">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__text">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +							<div class="card__text">
Используйте тег параграфа. div - элемент не имеющий семантического значения.

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +		<div class="footer__copy">
Используйте тег параграфа. div - элемент не имеющий семантического значения. Или для такого небольшого текстового содержимого подойдёт и тег span

2023-06-12 15:28 UTC, Avaakum commented on index.html
> +	<link rel="stylesheet" href="/fonts/fonts.css">
---

**Отлично:**

Правильный порядок подключения стилей и шрифтов. Шрифты нужно подключать перед стилями страницы, чтобы из-за специфичности  CSS уже подключенные шрифты использовались в стилях.

2023-06-12 15:28 UTC, Avaakum commented on styles/style.css
> +.footer__links li {
---

**Можно лучше:**

Можно задать этот стиль сразу для класса списка, и он будет иметь эффект на все элементы списка.

2023-06-13 17:41 UTC, ElenaDelhi commented
Исправила ошибки. Подскажите, почему не могу посмотреть результат по ссылке? https://elenadelhi.github.io/s-chistogo-lista/

2023-06-13 18:42 UTC, merged